<a href="https://colab.research.google.com/github/zzhining/ml_basic/blob/main/pandas/exercise/%EC%84%A0%ED%83%9D_%EB%B0%8F_%ED%8E%B8%EC%A7%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**A. 주어진 주가 데이터를 이용해 특정 조건에 맞는 데이터의 부분 집합을 추출하는 파이썬 코드를 작성하세요.**

|Date|Open|Close|High|Low|Volume|
|---|---|---|---|---|---|
|2024-06-06|152|155|158|151|3100000|
|2024-06-07|154|156|160|153|3300000|
|2024-06-08|157|159|161|156|3400000|
|2024-06-09|158|162|164|157|3200000|
|2024-06-10|160|161|163|159|3500000|
|2024-06-11|161|164|166|160|3600000|
|2024-06-12|159|162|165|158|3700000|
|2024-06-13|160|161|164|157|3800000|

In [1]:
data1 = {
    'Date': ['2024-06-06', '2024-06-07', '2024-06-08', '2024-06-09', '2024-06-10', '2024-06-11', '2024-06-12', '2024-06-13'],
    'Open': [152, 154, 157, 158, 160, 161, 159, 160],
    'Close': [155, 156, 159, 162, 161, 164, 162, 161],
    'High': [158, 160, 161, 164, 163, 166, 165, 164],
    'Low': [151, 153, 156, 157, 159, 160, 158, 157],
    'Volume': [3100000, 3300000, 3400000, 3200000, 3500000, 3600000, 3700000, 3800000]
}

In [5]:
import pandas as pd
df = pd.DataFrame(data1)
df

Date  Open  Close  High  Low   Volume
0  2024-06-06   152    155   158  151  3100000
1  2024-06-07   154    156   160  153  3300000
2  2024-06-08   157    159   161  156  3400000
3  2024-06-09   158    162   164  157  3200000
4  2024-06-10   160    161   163  159  3500000
5  2024-06-11   161    164   166  160  3600000
6  2024-06-12   159    162   165  158  3700000
7  2024-06-13   160    161   164  157  3800000

1. 'Volume' 열의 값이 3500000 이상인 행(row)들을 추출하여 새로운 데이터프레임을 만드세요.

In [7]:
#답을 작성하세요.
df[df['Volume']>=3500000]

Date  Open  Close  High  Low   Volume
4  2024-06-10   160    161   163  159  3500000
5  2024-06-11   161    164   166  160  3600000
6  2024-06-12   159    162   165  158  3700000
7  2024-06-13   160    161   164  157  3800000

2. 'Close' 열의 값이 160 이상이고 'High' 열의 값이 165 이하인 행(row)들을 추출하여 새로운 데이터프레임을 만드세요.

In [11]:
#답을 작성하세요.
df[(df['Close'] >= 160) & (df['High'] <=165)]

Date  Open  Close  High  Low   Volume
3  2024-06-09   158    162   164  157  3200000
4  2024-06-10   160    161   163  159  3500000
6  2024-06-12   159    162   165  158  3700000
7  2024-06-13   160    161   164  157  3800000

3. 'Date'가 '2024-06-08' 이후인 행(row)들을 추출하여 새로운 데이터프레임을 만드세요.


In [15]:
#답을 작성하세요.
df[df['Date'] > '2024-06-08'] 

Date  Open  Close  High  Low   Volume
3  2024-06-09   158    162   164  157  3200000
4  2024-06-10   160    161   163  159  3500000
5  2024-06-11   161    164   166  160  3600000
6  2024-06-12   159    162   165  158  3700000
7  2024-06-13   160    161   164  157  3800000

4. 'Date', 'High', 'Low', 'Diff' 만을 갖는 데이터 프레임 중, 'Diff'의 값이 7 이상인 데이터만 추출하는 데이터프레임을 만드세요. (Diff는 'High' - 'Low')

In [35]:
#답을 작성하세요.
df['Diff'] = df['High'] - df['Low']
answer = df[['Date', 'High', 'Low', 'Diff']]
answer

Date  High  Low  Diff
0  2024-06-06   158  151     7
1  2024-06-07   160  153     7
2  2024-06-08   161  156     5
3  2024-06-09   164  157     7
4  2024-06-10   163  159     4
5  2024-06-11   166  160     6
6  2024-06-12   165  158     7
7  2024-06-13   164  157     7

In [36]:
answer[answer['Diff']>=7]

Date  High  Low  Diff
0  2024-06-06   158  151     7
1  2024-06-07   160  153     7
3  2024-06-09   164  157     7
6  2024-06-12   165  158     7
7  2024-06-13   164  157     7

**B. 주어진 주가 데이터를 이용해 특정 조건에 맞는 데이터의 부분 집합을 추출하는 파이썬 코드를 작성하세요.**

|Date|Open|Close|High|Low|Volume|
|---|---|---|---|---|---|
|2024-06-01|152|155|158|151|3100000|
|2024-06-02|154|156|160|153|3300000|
|2024-06-03|157|159|161|156|3400000|
|2024-06-03|157|159|161|156|3400000|
|2024-06-04|158|162|164|157|3200000|
|2024-06-05|160|161|163|159|3500000|
|2024-06-05|160|161|163|159|3500000|

In [55]:
data2 = {
    'Date': ['2024-06-01', '2024-06-02', '2024-06-03', '2024-06-03', '2024-06-04', '2024-06-05', '2024-06-05'],
    'Open': [152, 154, 157, 157, 158, 160, 160],
    'Close': [155, 156, 159, 159, 162, 161, 161],
    'High': [158, 160, 161, 161, 164, 163, 163],
    'Low': [151, 153, 156, 156, 157, 159, 159],
    'Volume': [3100000, 3300000, 3400000, 3400000, 3200000, 3500000, 3500000]
}

5. 위 데이터에서 중복된 데이터의 개수를 출력하는 코드를 만드세요.

In [69]:
#답을 작성하세요.
df2 = pd.DataFrame(data2)
df2

Date  Open  Close  High  Low   Volume
0  2024-06-01   152    155   158  151  3100000
1  2024-06-02   154    156   160  153  3300000
2  2024-06-03   157    159   161  156  3400000
3  2024-06-03   157    159   161  156  3400000
4  2024-06-04   158    162   164  157  3200000
5  2024-06-05   160    161   163  159  3500000
6  2024-06-05   160    161   163  159  3500000

In [70]:
duplicated_df = df2.duplicated().sum()
duplicated_df

2

6. 중복된 행(row)을 제거한 데이터프레임을 만드세요.

In [60]:
#답을 작성하세요.
dropped_duplicates = df2.drop_duplicates()
dropped_duplicates

Date  Open  Close  High  Low   Volume
0  2024-06-01   152    155   158  151  3100000
1  2024-06-02   154    156   160  153  3300000
2  2024-06-03   157    159   161  156  3400000
4  2024-06-04   158    162   164  157  3200000
5  2024-06-05   160    161   163  159  3500000

7. 중복된 행을 제거하기 전과 후의 데이터프레임의 크기를 출력하세요.

In [61]:
#답을 작성하세요.
df2.shape

(7, 6)

In [62]:
dropped_duplicates.shape

(5, 6)

@. data2에서 'Volume' 열이 3500000인 행을 제거한 후, 날짜('Date')와 'Close' 열을 기준으로 중복된 행을 제거하세요. 중복된 행이 여러 개 있다면 가장 최근의 행을 유지하는 코드를 만드세요

In [79]:
# 답을 작성하세요
updated_df2 = df2[df2['Volume'] != 3500000]
updated_df2

Date  Open  Close  High  Low   Volume
0  2024-06-01   152    155   158  151  3100000
1  2024-06-02   154    156   160  153  3300000
2  2024-06-03   157    159   161  156  3400000
3  2024-06-03   157    159   161  156  3400000
4  2024-06-04   158    162   164  157  3200000

In [80]:
updated_df2.drop_duplicates(df[['Date', 'Close']])

Date  Open  Close  High  Low   Volume
0  2024-06-01   152    155   158  151  3100000
1  2024-06-02   154    156   160  153  3300000
2  2024-06-03   157    159   161  156  3400000
4  2024-06-04   158    162   164  157  3200000

In [ ]:
df_filtered = df[df['Volume'] != 3500000].drop_duplicates(subset=['Date', 'Close'], keep='last')